# Generated by Django 5.0.6 on 2024-10-02 11:10

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2), users.models.validate_name], verbose_name='username')),
                ('info', models.TextField(blank=True, help_text='Введите дополнительную информацию', null=True, verbose_name='Информация')),
                ('email', models.EmailField(help_text='Введите email, не более 50 символов', max_length=50, unique=True, verbose_name='Почта')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Бан')),
                ('banned_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала бана')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=400, null=True)),
                ('key_to_recepient', models.CharField(blank=True, max_length=50, null=True, verbose_name='Enter id or email of the user')),
                ('viewed', models.BooleanField(default=False, verbose_name='Прочитано/Не прочитано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Одноразовый код')),
                ('count_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('count_send_code', models.PositiveSmallIntegerField(default=0, verbose_name='Количество повторных отправок кода')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления кода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания кода')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onetimecodes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'одноразовый код',
                'verbose_name_plural': 'Одноразовые коды',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^(\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?$', 'The phone number provided is invalid')], verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), users.models.validate_name], verbose_name='Имя пользователя')),
                ('object_id', models.PositiveIntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(50, 30), srid=4326)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
