# Generated by Django 5.0.6 on 2024-09-27 13:24

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Введите email, не более 50 символов', max_length=50, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2), users.models.validate_name], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), users.models.validate_name], verbose_name='Имя пользователя'),
        ),
    ]
