# Generated by Django 5.0.6 on 2024-05-31 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='customuser',
            name='info',
            field=models.TextField(blank=True, help_text='Введите дополнительную информацию', null=True, verbose_name='Информация'),
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Одноразовый код')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Код подтвержден')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'одноразовый код',
                'verbose_name_plural': 'Одноразовые коды',
                'ordering': ('id',),
            },
        ),
    ]
