# Generated by Django 5.0.6 on 2024-10-14 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{6,15}$')], verbose_name='Номер телефона'),
        ),
    ]
