# Generated by Django 5.0.6 on 2024-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Прочитано/Не прочитано'),
        ),
    ]
