# Generated by Django 5.0.6 on 2024-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_onetimecode_remaining_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first',
            field=models.BooleanField(default=True, verbose_name='Первый вход'),
        ),
    ]
