# Generated by Django 5.0.6 on 2024-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_banned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='count_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попытки'),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='count_send_code',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество повторных отправок кода'),
        ),
    ]
