# Generated by Django 5.0.6 on 2024-06-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_onetimecode_count_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_first',
        ),
    ]
