# Generated by Django 5.0.6 on 2024-09-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_content_type_customuser_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='object_id',
        ),
    ]
