# Generated by Django 5.0.6 on 2024-06-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
