# Generated by Django 5.0.6 on 2024-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banned_at',
            field=models.DateTimeField(default=None, verbose_name='Время бана'),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания кода'),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления кода'),
        ),
    ]
