# Generated by Django 5.0.6 on 2024-06-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_banned_at_alter_onetimecode_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='banned_at',
        ),
    ]
