# Generated by Django 5.0.6 on 2024-06-04 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_banned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время бана'),
            preserve_default=False,
        ),
    ]
