# Generated by Django 5.0.6 on 2024-06-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_banned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimecode',
            name='is_verified',
        ),
    ]
