# Generated by Django 5.0.6 on 2024-06-04 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_onetimecode_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otc', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
