# Generated by Django 5.0.6 on 2024-06-07 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_onetimecode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='remaining_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Оставшиеся попытки'),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onetimecodes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
