# Generated by Django 5.0.6 on 2024-06-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_onetimecode_remaining_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimecode',
            old_name='remaining_attempts',
            new_name='count_attempts',
        ),
    ]
