# Generated by Django 5.0.6 on 2024-06-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_remaining_attempts_onetimecode_count_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='count_attempts',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Оставшиеся попытки'),
        ),
    ]
