# Generated by Django 5.0.6 on 2024-06-08 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customuser_is_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='banned_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
    ]
