# Generated by Django 5.0.6 on 2024-06-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='count_attempts',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Попытки'),
        ),
    ]
