# Generated by Django 5.0.6 on 2024-06-12 16:46

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customuser_username_en_customuser_username_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username_en',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username_es',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username_ru',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_en',
            field=models.EmailField(help_text='Введите email, не более 254 символов', max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_es',
            field=models.EmailField(help_text='Введите email, не более 254 символов', max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_ru',
            field=models.EmailField(help_text='Введите email, не более 254 символов', max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
