# Generated by Django 5.0.6 on 2024-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_customuser_username_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first',
            field=models.BooleanField(default=True, verbose_name='Первый вход'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
