# Generated by Django 5.0.6 on 2024-06-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customuser_is_first_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='count_send_code',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Количество повторных отправок кода'),
        ),
    ]
