services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  server:
    image: nginx
    restart: always
    depends_on:
      - web
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./templates:/etc/nginx/templates
      - ./static:/static/
  web:
    container_name: web
    image: andreymazo/bulletin_board_backend_web:1.0
  
    env_file:
      .env.dev
    environment:
      - REDIS_HOST=redis  
    tty: true
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
        
      redis:
        condition: service_started
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata --exclude contenttypes db.json  && gunicorn config.wsgi:application --bind 0.0.0.0:8000 "  
  celery:
    image: andreymazo/bulletin_board_backend_celery:1.0
    env_file:
      .env.dev
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: >
       sh -c "python manage.py migrate django_celery_beat && celery -A config worker --beat --scheduler django --loglevel=info"
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  celery-beat:
    image: andreymazo/bulletin_board_backend_celery-beat:1.0
    volumes:
      - .:/code
    depends_on:
      # db:
      #   condition: service_healthy
      # redis:
      #   condition: service_started
       
      - db
      - redis
      - celery
   
  db:
    container_name: db
    image: andreymazo/bulletin_board_backend_db:1.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: bulletin
    env_file:
      - .env.dev
    ports:
      - '5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - database_volume:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d bulletin'"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  database_volume: