version: '3'
services:
  db:
      container_name: db
      build:
        context: .
        dockerfile: Dockerfile-db
      # restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "123456"
        POSTGRES_DB: bulletin
        # - "POSTGRES_HOST_AUTH_METHOD=trust"
      env_file:
        - .env.dev
      ports:
         - "5447:5432"
      volumes:
        - ./db:/docker-entrypoint-initdb.d/
        - database_volume:/var/lib/postgresql/data
      networks:
        - djangonetwork
      
      healthcheck:
        test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d bulletin'"]
        interval: 5s
        timeout: 5s
        retries: 5
    
volumes:
  database_volume:
networks:
  djangonetwork:
    driver: bridge