# Generated by Django 5.0.6 on 2024-06-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
