# Generated by Django 5.0.6 on 2024-06-28 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_initial'),
        ('users', '0006_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='marker', to='users.profile', verbose_name='profile'),
            preserve_default=False,
        ),
    ]
