# Generated by Django 5.0.6 on 2024-07-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_marker_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='profile',
        ),
    ]
