# Generated by Django 5.0.6 on 2024-09-22 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menshoes',
            name='size',
            field=models.CharField(choices=[('6', '36'), ('6.5', '37'), ('7', '38'), ('7.5', '39'), ('8', '40'), ('8.5', '41'), ('9', '42'), ('9.5', '43'), ('10', '44'), ('10.5', '45'), ('11', '46'), ('11.5', '47'), ('12', '48')], default='9.5'),
        ),
        migrations.AddField(
            model_name='wemenclothes',
            name='size',
            field=models.CharField(choices=[('XS—34/36', 'особо маленький - extra small'), ('S — 38/40', 'маленький - small'), ('M—42/44', 'средний - medium'), ('L— 46/48', 'большой - large'), ('XL—50/52', 'особо большой — extra large'), ('XXL—54/56', 'особо особо большой — extra-extra large'), ('3XL—58/60', 'особо особо особо большой — extra-extra-extra large')], default='M—42/44'),
        ),
        migrations.AddField(
            model_name='wemenshoes',
            name='size',
            field=models.CharField(choices=[('4', '34'), ('4.5', '35'), ('5', '36'), ('5.5', '37'), ('6', '38'), ('6.5', '39'), ('7', '40'), ('7.5', '41'), ('8', '42'), ('8.5', '43'), ('9', '44'), ('9.5', '45'), ('10', '46')], default='7.5'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
