# Generated by Django 5.0.6 on 2024-09-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
