# Generated by Django 5.0.6 on 2024-06-20 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_advertisement_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='changed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
