# Generated by Django 5.0.6 on 2024-10-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsknapsacks',
            name='title',
            field=models.CharField(default='smthing for default', max_length=150, verbose_name="Document'stitle"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(default='smthing for default', max_length=150, verbose_name="Document'stitle"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childclothesshoes',
            name='title',
            field=models.CharField(default='smthing for default', max_length=150, verbose_name="Document'stitle"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menclothes',
            name='title',
            field=models.CharField(default='smthing for default', max_length=150, verbose_name="Document'stitle"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='title',
            field=models.CharField(default='smthing for default', max_length=150, verbose_name="Document'stitle"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wemenclothes',
            name='title',
            field=models.CharField(default='smthing for default', max_length=150, verbose_name="Document'stitle"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wemenshoes',
            name='title',
            field=models.CharField(default='smthing for default', max_length=150, verbose_name="Document'stitle"),
            preserve_default=False,
        ),
    ]
