# Generated by Django 5.0.6 on 2024-09-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_menshoes_size_wemenclothes_size_wemenshoes_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menclothes',
            name='size',
            field=models.CharField(choices=[('XS—40/42', 'особо маленький - extra small'), ('S — 44/46', 'маленький - small'), ('M—48/50', 'средний - medium'), ('L— 52/54', 'большой - large'), ('XL—56/58', 'особо большой — extra large'), ('XXL— 60/62', 'особо особо большой— extra-extra large'), ('3XL—64/66', 'особо особо особо большой— extra-extra-extra large')]),
        ),
    ]
