# Generated by Django 5.0.6 on 2024-06-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_advertisement_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='name',
            new_name='title',
        ),
    ]
