# Generated by Django 5.0.6 on 2024-09-09 13:38

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_remove_bagsknapsacks_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagsknapsacks',
            name='category',
            field=mptt.fields.TreeForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='bagknapsacks', to='ad.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childclothesshoes',
            name='category',
            field=mptt.fields.TreeForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='childclothesshoes', to='ad.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menclothes',
            name='category',
            field=mptt.fields.TreeForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, related_name='menclothes', to='ad.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menshoes',
            name='category',
            field=mptt.fields.TreeForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='menshoes', to='ad.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wemenclothes',
            name='category',
            field=mptt.fields.TreeForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='wemenclothes', to='ad.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wemenshoes',
            name='category',
            field=mptt.fields.TreeForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='wemenshoes', to='ad.category'),
            preserve_default=False,
        ),
    ]
