# Generated by Django 5.0.6 on 2024-09-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_car_archived_bagsknapsacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildClothesShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name="Document'stitle")),
                ('created', models.DateTimeField(auto_now=True)),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивное')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Child's Clothes&Shoes",
                'verbose_name_plural': "Child's Clothes&Shoes",
            },
        ),
        migrations.RemoveField(
            model_name='bagsknapsacks',
            name='profile',
        ),
    ]
