# Generated by Django 5.0.6 on 2024-09-09 16:00

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_bagsknapsacks_category_childclothesshoes_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsknapsacks',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagsknapsacks', to='ad.category'),
        ),
    ]
