# Generated by Django 5.0.6 on 2024-09-06 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_childclothesshoes_remove_bagsknapsacks_profile'),
        ('users', '0005_remove_customuser_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagsknapsacks',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bagsknapsacks', to='users.profile'),
        ),
    ]
