# Generated by Django 5.0.6 on 2024-09-21 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_alter_bagsknapsacks_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsknapsacks',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='childclothesshoes',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='menclothes',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='wemenclothes',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='wemenshoes',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
    ]
