# Generated by Django 5.0.6 on 2024-09-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_bagsknapsacks_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name="Document'stitle")),
                ('created', models.DateTimeField(auto_now=True)),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивное')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('size', models.CharField(choices=[('XS—40/42', 'особо маленький - extra small'), ('S — 44/46', 'маленький - small'), ('(M—48/50', 'средний - medium'), ('L— 52/54', 'большой - large'), ('XL—56/58', 'особо большой — extra large'), ('XXL— 60/62', ' особо особо большой— extra-extra large'), ('3XL—64/66', 'ососбо особо особо большой— extra-extra-extra large')])),
            ],
            options={
                'verbose_name': 'Men Clothes',
                'verbose_name_plural': 'Men Clothes',
            },
        ),
        migrations.CreateModel(
            name='MenShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name="Document'stitle")),
                ('created', models.DateTimeField(auto_now=True)),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивное')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Men Shoes',
                'verbose_name_plural': 'Men Shoes',
            },
        ),
        migrations.CreateModel(
            name='WemenClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name="Document'stitle")),
                ('created', models.DateTimeField(auto_now=True)),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивное')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Automobile',
                'verbose_name_plural': 'Automobiles',
            },
        ),
        migrations.CreateModel(
            name='WemenShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name="Document'stitle")),
                ('created', models.DateTimeField(auto_now=True)),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивное')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Wemen Shoes',
                'verbose_name_plural': 'Wemen Shoes',
            },
        ),
        migrations.RemoveField(
            model_name='bagsknapsacks',
            name='profile',
        ),
    ]
