# Generated by Django 5.0.6 on 2024-09-21 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_alter_bagsknapsacks_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wemenclothes',
            options={'verbose_name': 'Women Clothes', 'verbose_name_plural': 'Women Clothes'},
        ),
        migrations.AlterModelOptions(
            name='wemenshoes',
            options={'verbose_name': 'Women Shoes', 'verbose_name_plural': 'Women Shoes'},
        ),
        migrations.AlterField(
            model_name='bagsknapsacks',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='childclothesshoes',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='menclothes',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='wemenclothes',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='wemenshoes',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='price'),
        ),
    ]
