# Generated by Django 5.0.6 on 2024-06-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_remove_documents_advertisement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
    ]
