# Generated by Django 5.0.6 on 2024-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_images_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='changed',
        ),
        migrations.RemoveField(
            model_name='images',
            name='created',
        ),
        migrations.RemoveField(
            model_name='images',
            name='moderation',
        ),
        migrations.RemoveField(
            model_name='images',
            name='profile',
        ),
        migrations.AlterField(
            model_name='auto',
            name='by_mileage',
            field=models.CharField(choices=[('ALL', 'ALL'), ('NEW', 'NEW'), ('WM', 'With Mileage')], verbose_name='Differ by mileage'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='by_wheel_drive',
            field=models.CharField(blank=True, choices=[('FWD', 'FRONT_WHEEL_DRIVE'), ('RWD', 'REAR_WHEEL_DRIVE'), ('4WD', 'VARIATOR')], null=True, verbose_name='Differ by wheel drive'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='colour',
            field=models.CharField(blank=True, choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('GREY', 'GREY'), ('RED', 'RED'), ('ORANGE', 'ORANGE'), ('BEIGE', 'BEIGE'), ('BROWN', 'BROWN')], null=True, verbose_name='Differ by colour'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='fuel',
            field=models.CharField(blank=True, choices=[('PTR', 'PETROL'), ('GAS', 'GAS'), ('HYBRID', 'HYBRID'), ('ELECTRIC', 'ELECTRIC'), ('DIESEL', 'DIESEL')], null=True, verbose_name='Differ by fuel'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='transmission',
            field=models.CharField(blank=True, choices=[('A', 'AUTO'), ('R', 'ROBOT'), ('V', 'VARIATOR'), ('M', 'MECHANICAL')], null=True, verbose_name='Differ by transmission'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='type',
            field=models.CharField(blank=True, choices=[('SD', 'SEDAN'), ('UN', 'UNIVERSAL'), ('OR', 'OFF_ROAD'), ('HTB', 'HATCHBACK')], null=True, verbose_name='Differ by type'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to='media/documents', verbose_name="Document's title"),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='media/images', verbose_name='Photo'),
        ),
    ]
