# Generated by Django 5.0.6 on 2024-06-23 14:41

import ad.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_remove_images_changed_remove_images_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), ad.models.max_value_current_year], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Document's title"),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Photoe's title"),
        ),
    ]
