# Generated by Django 5.0.6 on 2024-06-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_alter_auto_year_alter_documents_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='auto',
        ),
    ]
