# Generated by Django 5.0.6 on 2024-06-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_remove_ip_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='auto',
        ),
    ]
