# Generated by Django 5.0.6 on 2024-06-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0012_remove_documents_auto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
