# Generated by Django 5.0.6 on 2024-06-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0014_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.auto'),
        ),
        migrations.AddField(
            model_name='images',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.auto'),
        ),
        migrations.AddField(
            model_name='ip',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.auto'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Document'stitle"),
        ),
    ]
