# Generated by Django 5.0.6 on 2024-09-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0014_car_content_type_car_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description_ru',
        ),
    ]
