# Generated by Django 5.0.6 on 2024-09-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0015_remove_car_description_en_remove_car_description_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='profile',
        ),
    ]
