# Generated by Django 5.0.6 on 2024-06-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0016_images_changed_images_created_images_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='description_en',
            field=models.CharField(max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='auto',
            name='description_es',
            field=models.CharField(max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='auto',
            name='description_ru',
            field=models.CharField(max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
