# Generated by Django 5.0.6 on 2024-06-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0017_auto_description_en_auto_description_es_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Automobile', 'verbose_name_plural': 'Automobiles'},
        ),
    ]
