# Generated by Django 5.0.6 on 2024-06-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0019_auto_category'),
        ('users', '0006_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto',
            new_name='Car',
        ),
    ]
