# Generated by Django 5.0.6 on 2024-06-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0020_rename_auto_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/images', verbose_name='Photo'),
        ),
    ]
