# Generated by Django 5.0.6 on 2024-06-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0021_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Photo'),
        ),
    ]
