# Generated by Django 5.0.6 on 2024-06-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0022_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='auto',
        ),
        migrations.AddField(
            model_name='images',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ad.car'),
        ),
    ]
