# Generated by Django 5.0.6 on 2024-07-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0025_remove_like_likes_like_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ad.card'),
        ),
    ]
