# Generated by Django 5.0.6 on 2024-07-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0026_alter_like_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='images',
            name='car',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='card',
            name='marker',
        ),
        migrations.RemoveField(
            model_name='card',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='like',
            name='card',
        ),
        migrations.RemoveField(
            model_name='images',
            name='card',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
