# Generated by Django 5.0.6 on 2024-07-15 21:10

import ad.models
import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0027_remove_ip_auto_remove_images_car_and_more'),
        ('map', '0007_remove_marker_profile'),
        ('users', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name="Document'stitle")),
                ('created', models.DateTimeField(auto_now=True)),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('by_mileage', models.CharField(choices=[('ALL', 'ALL'), ('NEW', 'NEW'), ('WM', 'With Mileage')], verbose_name='Differ by mileage')),
                ('brand', models.CharField(max_length=100, verbose_name='brand')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('year', models.PositiveSmallIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), ad.models.max_value_current_year], verbose_name='year')),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(blank=True, choices=[('A', 'AUTO'), ('R', 'ROBOT'), ('V', 'VARIATOR'), ('M', 'MECHANICAL')], null=True, verbose_name='Differ by transmission')),
                ('by_wheel_drive', models.CharField(blank=True, choices=[('FWD', 'FRONT_WHEEL_DRIVE'), ('RWD', 'REAR_WHEEL_DRIVE'), ('4WD', 'VARIATOR')], null=True, verbose_name='Differ by wheel drive')),
                ('engine_capacity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='engine capacity')),
                ('engine_power', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(900)], verbose_name='engine power in horse power')),
                ('fuel_consumption', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='fuel consumption per 100 km')),
                ('location', models.CharField(blank=True, max_length=160, null=True, verbose_name='location')),
                ('type', models.CharField(blank=True, choices=[('SD', 'SEDAN'), ('UN', 'UNIVERSAL'), ('OR', 'OFF_ROAD'), ('HTB', 'HATCHBACK')], null=True, verbose_name='Differ by type')),
                ('colour', models.CharField(blank=True, choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('GREY', 'GREY'), ('RED', 'RED'), ('ORANGE', 'ORANGE'), ('BEIGE', 'BEIGE'), ('BROWN', 'BROWN')], null=True, verbose_name='Differ by colour')),
                ('fuel', models.CharField(blank=True, choices=[('PTR', 'PETROL'), ('GAS', 'GAS'), ('HYBRID', 'HYBRID'), ('ELECTRIC', 'ELECTRIC'), ('DIESEL', 'DIESEL')], null=True, verbose_name='Differ by fuel')),
                ('add_parametres', models.CharField(blank=True, max_length=150, null=True, verbose_name='additional')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('description_es', models.CharField(max_length=2000, null=True, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=2000, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=2000, null=True, verbose_name='Description')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='ad.category')),
                ('marker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='map.marker')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'Automobile',
                'verbose_name_plural': 'Automobiles',
            },
        ),
        migrations.AddField(
            model_name='documents',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.car'),
        ),
        migrations.AddField(
            model_name='images',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ad.car'),
        ),
        migrations.AddField(
            model_name='ip',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.car'),
        ),
    ]
