# Generated by Django 5.0.6 on 2024-07-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0028_car_documents_auto_images_car_ip_auto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
