# Generated by Django 5.0.6 on 2024-07-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0032_remove_images_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
