# Generated by Django 5.0.6 on 2024-07-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0034_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='marker',
        ),
    ]
