# Generated by Django 5.0.6 on 2024-07-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0036_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='key_to_recepient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Enter id or email of the user'),
        ),
    ]
