# Generated by Django 5.0.6 on 2024-07-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0037_alter_notification_key_to_recepient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
