# Generated by Django 5.0.6 on 2024-07-25 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0038_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='time_paied',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
