# Generated by Django 5.0.6 on 2024-07-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0039_promotion_time_paied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='images',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='profile',
        ),
    ]
