# Generated by Django 5.0.6 on 2024-07-28 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0042_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='car',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='ad.car'),
            preserve_default=False,
        ),
    ]
