# Generated by Django 5.0.6 on 2024-07-28 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0043_views_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='ad.car'),
        ),
    ]
