# Generated by Django 5.0.6 on 2024-07-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0044_alter_views_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='num_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
