# Generated by Django 5.0.6 on 2024-07-28 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0045_alter_views_num_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='views',
            name='car',
        ),
        migrations.AddField(
            model_name='views',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='ad.ip'),
        ),
    ]
