# Generated by Django 5.0.6 on 2024-07-28 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0046_remove_views_car_views_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view', to='ad.ip'),
        ),
    ]
