# Generated by Django 5.0.6 on 2024-07-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0047_alter_views_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='views',
            name='ip',
        ),
    ]
