# Generated by Django 5.0.6 on 2024-07-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0049_views_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='views',
            name='num_views',
        ),
    ]
