# Generated by Django 5.0.6 on 2024-07-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0050_remove_views_num_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Views',
        ),
    ]
