# Generated by Django 5.0.6 on 2024-08-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0053_car_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photos',
        ),
    ]
