# Generated by Django 5.0.6 on 2024-08-24 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mssg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=400, null=True)),
                ('key_to_recepient', models.CharField(blank=True, max_length=50, null=True, verbose_name='Enter id or email of the user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mssg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
