# Generated by Django 5.0.6 on 2024-08-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_mssg_content_type_mssg_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mssg',
            name='text',
            field=models.CharField(default='something here', max_length=400),
            preserve_default=False,
        ),
    ]
