# Generated by Django 5.0.6 on 2024-08-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='owner',
            new_name='user',
        ),
    ]
