MAX_LEN_CODE = 5
MAX_LEN_USERNAME = 150
MAX_LEN_EMAIL = 254
MAX_LEN_PHONE_NUMBER = 12
MAX_LEN_NAME_PROFILE = 150
COUNT_ATTEMPTS = 3
TIME_OTC = 30 * 60  # Время жизни кода в секундах
TIME_RESEND_CODE = 3 * 60  # Время между повторными отправками кода
COUNT_SEND_CODE = 3
LEN_CODE = 5
TIME_BAN = 24 * 60 * 60  # Время бана в секундах
MAX_LEN_NAME_CATEGORY = 50
