# Generated by Django 5.0.6 on 2024-06-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала бана'),
        ),
    ]
