# Generated by Django 5.0.6 on 2024-09-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0003_notification_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='content_type',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='object_id',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
