# Generated by Django 5.0.6 on 2024-09-06 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0005_remove_customuser_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content_type',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='object_id',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
