# Generated by Django 5.0.6 on 2024-09-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_content_type_profile_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
