# Generated by Django 5.0.6 on 2024-07-25 22:37

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Point

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(23, 35), srid=4326),
            preserve_default=False,
        ),
    ]
