# Generated by Django 5.0.6 on 2024-08-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
