# Generated by Django 5.0.6 on 2024-09-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_remove_favorite_user'),
        ('users', '0005_remove_customuser_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивное'),
        ),
        migrations.CreateModel(
            name='BagsKnapsacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name="Document'stitle")),
                ('created', models.DateTimeField(auto_now=True)),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивное')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='users.profile')),
            ],
            options={
                'verbose_name': 'Bags&Knapsacks',
                'verbose_name_plural': 'Bags&Knapsacks',
            },
        ),
    ]
