# Generated by Django 5.0.6 on 2024-07-24 22:18

import ad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0035_remove_car_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(storage=ad.models.OverwriteStorage(), upload_to='images', verbose_name='Photo'),
        ),
    ]
