# Generated by Django 5.0.6 on 2024-07-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0036_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Photo'),
        ),
    ]
